### PR TITLE
NOTIF-499 Allow to specify an ID on the incoming messages.

### PR DESCRIPTION
**Pull request by pilhuhn**
Don't force its use yet

### CODE REVIEW

**Comment by pilhuhn** [comment]
I think there may still be something wrong, as when I use this (in engine), always a schema without the additonal 'id' is pulled in and thus validation fails. @josejulio Do you have an idea?

**Comment by josejulio** [comment]
> I think there may still be something wrong, as when I use this (in engine), always a schema without the additonal 'id' is pulled in and thus validation fails. @josejulio Do you have an idea?

Could you share what you do when it fails? You are using this version in the engine and it fails to send a message? Not sure if it's about the `uuid`, but should fail the serialization tests without the `id`.

**Comment by pilhuhn** [comment]
@josejulio Looks like my running code is still pulling in 0.8 through some odd dependency resolution even if the IDE tells me that I am using the modified code. A full rebuild that also updated the parent/pom.xml in my local ~/.m2/repo  seems to have fixed the issue

**Review by josejulio — APPROVED** [review]
lgtm

**Pull request merged**
